version: '3.8'

services:
  postgres:
    container_name: DB-TCC
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: tcc
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
  # PostgreSQL to tests
  postgres_test:
    container_name: DB-TCC-TEST
    image: postgres
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: tcc-test
      PGDATA: /data/postgres
    volumes:
      - ./data/pg_test:/data/postgres
